version: '3.8'

services:
  desafio-fullstack-backend:
    container_name: desafio-fullstack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Expondo apenas a porta 5000 para HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - desafio-network

  desafio-fullstack-frontend:
    container_name: desafio-fullstack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - desafio-fullstack-backend
    networks:
      - desafio-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: desafio-fullstack-sqlserver
    environment:
      SA_PASSWORD: "Strong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
